### ISSUE TITLE
Broken reverse dependencies since 1.0.0

### ISSUE THREAD

**Issue by hasufell** [haskell/base16-bytestring#14]
I believe the release broke at least:

* https://hackage.haskell.org/package/text-conversions

and as a consequence all deps that depend on text-conversions:

* https://gitlab.com/williamyaoh/string-interpolate/-/issues/27

and all deps that depend on string-interpolate:

* https://gitlab.haskell.org/haskell/ghcup-hs/-/jobs/444976

----

Yes, I believe checking reverse dependencies is what we should do before a release: https://packdeps.haskellers.com/reverse/base16-bytestring

This will just be a revision update, so a hackage trustee could unbreak this. @phadej ?

**Comment by phadej** [comment]
@hasufell, I have stepped down as being Hackage Trustee.

**Comment by gwils** [comment]
I also stepped down from trusteeship.
@emilypi

**Comment by emilypi** [comment]
I'm not a trustee, but I'm happy to help @hasufell

**Comment by emilypi** [comment]
Ahahaaaa fuck me this is *exactly* why this change was needed. From `text-conversions`: 

```haskell
instance FromText (Maybe (Base16 B.ByteString)) where
  fromText txt = case Base16.decode (T.encodeUtf8 txt) of
    (bs, "") -> Just $ Base16 bs
    (_,  _)  -> Nothing
```

**Comment by emilypi** [comment]
> Yes, I believe checking reverse dependencies is what we should do before a release: https://packdeps.haskellers.com/reverse/base16-bytestring

FWIW, i had the issue out for months, and I made two announcements publicly 3 months ago that i was going to make radical changes to the library. See: [here](https://www.reddit.com/r/haskell/comments/hcepjt/ann_base16bytestring0117/). 

Short of personally messaging each maintainer of a downstream dependency of this library, which is an unreasonable request to make of any maintainer, I did what I needed to do. It was everyone else who failed to pay attention.

**Comment by mightybyte** [comment]
@hasufell None of the packages you mention have upper bounds on base16-bytestring.  If they had appropriate PVP-compliant bounds, they would not have been broken by this release.  This is not a problem with base16-bytestring.  This is a problem with the downstream packages that failed to put appropriate version bounds.

I'm a huge advocate of backwards compatibility but from time to time breaking changes do make sense.  It is the downstream packages to use dependency bounds so that they will be robust in these situations.

**Comment by hasufell** [comment]
> This is not a problem with base16-bytestring. This is a problem with the downstream packages that failed to put appropriate version bounds.

We could have a long discussion about this, but either way... it isn't enforced and the end user doesn't really care who is to blame in my opinion. So I personally think checking reverse dependencies is something we should do, if it's reasonable.

**Comment by mightybyte** [comment]
@hasufell It's not enforced, so guess what...buyer beware.  And in this case the buyer is you.  If you depend on packages that don't put upper bounds, you're going to run into this eventually.

It's absolutely not reasonable to expect maintainers to check reverse dependencies.  This package has 160 reverse dependencies.  There's no way they can check them all.  Remember, they're doing this work for free.

**Comment by hasufell** [comment]
Well, I disagree with you on that. I'd have put up a build for those reverse deps on my PC and let it run over night. 160 deps isn't much in haskell and writing a script for that should be well feasible. That's also my experience as a linux distro maintainer.

I'm not putting blame on anyone, but explaining that CI can help with this as well. There are many ways to get PVP wrong and accidentially break reverse deps, even if there are upper bounds.

**Comment by mightybyte** [comment]
I don't care whether it's theoretically possible to do it in this case.  What you are describing simply doesn't scale.  There is no limit to how many people / packages can depend on your package.  It's patently absurd to suggest that upstream is responsible for the decisions of everyone downstream.  You know what is scalable?  Owning the implications of the dependencies that you choose to add to your project and the risks associated with them.

**Comment by emilypi** [comment]
Feel free to donate to my github sponsorship program with the amount needed to afford another box to run things. I am on an underpowered work laptop 99% of the time. The other 1% is spent ssh'ing into a $5 droplet. Neither can support routine CI builds of any magnitude (which is why I outsource to Travis!). I do not own a computer otherwise.

**Comment by hasufell** [comment]
> I don't care whether it's theoretically possible to do it in this case.

I'm aware that the haskell ecosystem is particularly eager in breaking API and offloading things to PVP. But I believe that didn't scale either: it's the reason we got cabal hell, stackage, nix-style builds, hackage revisions and other workarounds and coping tools. I don't think this is mainly an issue with the PVP spec, but the eagerness of breaking API in general and not using deprecation phases and maybe that one historical split in the community.

>  What you are describing simply doesn't scale.

Whether you believe in PVP or not... testing reverse deps is a good thing **if** you have the capacity. And we can talk somewhere else about scaling issues, because I believe these aren't hard issues. Again: Linux distros do this since a few decades. Stackage does this too, in small scope. We can define the scope for hackage too.

Also, it's true there are other ways to deal with this... and these go deeper into the tooling foxhole: https://dependabot.com/rust/

**Comment by mightybyte** [comment]
@hasufell I look forward to your contributions to improve the state of the CI for this package.

**Comment by cartazio** [comment]
has ANYONE pinged / opened a trustees ticket to track fixing rev deps? I no longer have the perms to do so, else i'd happily do the ecosystem surgery plus downstream notifications.

agreed that testing downstream clients that are publicly available is idea, but definitely resource intensive and requires tooling and actually support

**Comment by emilypi** [comment]
@cartazio yes: https://github.com/haskell-infra/hackage-trustees/issues/280

**Comment by hasufell** [comment]
@emilypi I have a few ideas. The first would be to write a script that fetches reverse deps and sets up a dummy project with all those as local packages and then forces the development version of the main library via cabal.project. The next step would be to compare failures to previous failures to see if there are actual regressions. This could first run on travis if the build time is less than 2 hours.

But given the partly negative reactions here, I'm not sure people are interested in that approach.

**Comment by mightybyte** [comment]
> I'm not sure people are interested in that approach.

I am not a maintainer of this package, so my comments have nothing to do with what the maintainers will accept.  @emilypi just said "I would enjoy using it", and "that would be very helpful".  That sounds like pretty clear openness to your suggestions to me.

**Comment by emilypi** [comment]
I think the utility of this conversation has run its course. F

@hasufell feel free to get in touch with me at my email to actually build the thing, and we can start off on the right foot in a more appropriate setting.
