### ISSUE TITLE
1.0.0.0 release planning

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/base16-bytestring#9]
We should do a new minor release that includes #8 soon-ish.

We can also decide to fix #6 while we're at it, in which case the version number should be 0.1.2.0.

**Comment by emilypi** [comment]
Counter-proposal: we rename this to "`1.0.0.0` release planning", and merge #10, which addresses + subsumes #8, and fixes #6.

**Comment by 23Skidoo** [comment]
Would it make sense in addition to 1.0.0.0 to do a 0.1.1.7 bugfix release that includes #8 only?

**Comment by emilypi** [comment]
Yeah i think that makes a lot of sense for everyone who's not going to want the breaking changes immediately.

**Comment by emilypi** [comment]
@hvr what do you think?

**Comment by emilypi** [comment]
Released v1.0.0.0 to hackage 🎉
